### ISSUE TITLE
Create a set of tests to include on the CI

### ISSUE THREAD

**Issue by LanderU** [aliasrobotics/aztarna#30]
I'm testing manually https://github.com/aliasrobotics/aztarna/pull/27, we should consider include tests that can be automatically done when we add new feature on our code, like: https://github.com/ros2/system_tests

Opinions?

**Comment by o-olalde** [comment]
We are working on the robocalypse and including unit testing for every module. We will include this for aztarna in the future.

**Comment by LanderU** [comment]
Great! Thanks for the answer @o-olalde!
